# src/AppBundle/Resources/config/doctrine/Task.orm.yml
AppBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        task_name:
            type: string
            length: 255
        priority:
            type: string
            length: 10
        created_at:
            type: datetime
        updated_at:
            type: datetime